### ISSUE TITLE
Error running main.m example file

### ISSUE THREAD

**Issue by matmasch** [carlosouto/Sparse-Matrix-Builder#1]
I am very happy to see a function to speed up the assembly of sparse matrices in MATLAB! I downloaded the code and tried to run the main.m example file.

I received the error below. I'm running Matlab 2014b on Windows 10.

Undefined function 'sparse' for input arguments of type 'uint32'.

Error in SparseMatrixBuilder/ToMatlabSparse (line 76)
            output = sparse(coo(:, 1), coo(:, 2), coo(:, 3), m, n);

Error in miniTest (line 43)
matrix.ToMatlabSparse()

**Comment by carlos-souto** [comment]
Hi,

`sparse` is a Matlab function available since R2006a ([doc sparse](https://www.mathworks.com/help/matlab/ref/sparse.html)).

It appears that `sparse` does not work with type `uint32`. Indeed this seems to be the case in R2020b as well:

```
>> sparse([1 2; 3 4])

ans =

   (1,1)        1
   (2,1)        3
   (1,2)        2
   (2,2)        4

>> sparse(uint32([1 2; 3 4]))
Error using sparse
Input matrix must be double or logical.
```

Moreover, sparse matrices using the `SparseMatrixBuilder` class store their elements as doubles (double precision real number).

You can try converting your data to type `double` by calling the `double` function and only then should you use the `SparseMatrixBuilder` class:

```
>> matrix = uint32([1 2; 3 4])

matrix =

  2×2 uint32 matrix

   1   2
   3   4

>> double(matrix)

ans =

     1     2
     3     4
```

**Comment by matmasch** [comment]
Thank you for your reply. From the main.m example, I added the top line. 

matrix=double(matrix)
matrix.ToMatlabSparse()


The resulting output error:

Error using double
Conversion to double from SparseMatrixBuilder is not possible.

Error in miniTest (line 43)
matrix=double(matrix)

The output is the following:
Error using double
Conversion to double from SparseMatrixBuilder is not possible.

Error in miniTest (line 43)
matrix=double(matrix)


The data passed to matrix was double.

**Comment by carlos-souto** [comment]
Conversion to `double` from `SparseMatrixBuilder` is not possible. What I suggested was to make sure the data fed to the `SparseMatrixBuilder` was in fact of type `double`. However, this is not the problem.

Please check if main.m works without modifications to this file. But first, you need to update 'SparseMatrixBuilder.m' from:

```
% to matlab sparse
function output = ToMatlabSparse(this)
    coo = this.ToCOO();
    m = this.Base.NumberOfRows;
    n = this.Base.NumberOfColumns;
    output = sparse(coo(:, 1), coo(:, 2), coo(:, 3), m, n);
end
```
to:

 ```
% to matlab sparse
function output = ToMatlabSparse(this)
    coo = this.ToCOO();
    m = double(this.Base.NumberOfRows);
    n = double(this.Base.NumberOfColumns);
    output = sparse(coo(:, 1), coo(:, 2), coo(:, 3), m, n);
end
```
(added the double function call for `m` and `n`).

I will update the repository now, if you want you should be able to download the code again and it should work.

**Comment by matmasch** [comment]
That modification to the ToMatlabSparse(this) function did the trick! Thanks!
